const root=document.querySelector('#knight-lab-root');
if(root){
root.innerHTML=`<section class="kl-shell"><div class="kl-toolbar"><div class="kl-identity"><span class="kl-badge">PLAYABLE</span><div><h3>견습기사 · 전진 → 수호 → 반격</h3><p>WASD/방향키 이동 · 1~5 스킬 · Q A/B 전환 · Space 시전 · R 재배치</p></div></div><div class="kl-loadout"><label>주무기 속성<select id="kl-element"><option value="steel">강철 · 경직</option><option value="fire">화염 · 점화</option><option value="ice">냉기 · 둔화</option><option value="lightning">번개 · 연쇄</option></select></label><label>보조무기 변형<select id="kl-offhand"><option value="echo">성벽의 메아리 · 2차 타격</option><option value="mark">결투의 문장 · 표식 연계</option><option value="return">회수 사슬 · 귀환 판정</option></select></label></div></div><div class="kl-layout"><aside class="kl-panel kl-skills"><div class="kl-panel-head"><div><span>SKILLS</span><b>견습기사 5스킬</b></div><button id="kl-help" class="kl-icon-btn">?</button></div><div id="kl-skill-list" class="kl-skill-list"></div><div id="kl-forms" class="kl-forms"></div><div id="kl-rule-card" class="kl-rule-card"></div><button id="kl-cast" class="kl-cast"><kbd>Space</kbd> 현재 스킬 시전</button></aside><main class="kl-stage-wrap"><div class="kl-stage-head"><div><span id="kl-stage-title">훈련 진형 · 군중전</span><small>A/B 역할과 장비 규칙을 실제 판정으로 비교하세요.</small></div><div class="kl-stage-actions"><button data-layout="duel">단일 정예</button><button data-layout="crowd">군중</button><button data-layout="line">직선 진형</button></div></div><div id="kl-frame" class="kl-canvas-frame" tabindex="0"><canvas id="kl-canvas" width="960" height="540"></canvas><div class="kl-hud"><div class="kl-hp"><span id="kl-hp-fill"></span><b id="kl-hp-text">100 / 100</b></div><div id="kl-status" class="kl-status">준비</div></div><div id="kl-hotbar" class="kl-hotbar"></div><div id="kl-toast" class="kl-toast"></div></div><div class="kl-combat-readout"><div><span>현재 스킬</span><b id="kl-read-skill"></b></div><div><span>속성</span><b id="kl-read-element"></b></div><div><span>보조 규칙</span><b id="kl-read-offhand"></b></div><div><span>최근 피해</span><b id="kl-read-damage">0</b></div></div></main></div><div class="kl-log-wrap"><div class="kl-log-title"><b>전투 로그</b><span>플레이 변화가 먼저 느껴지는지 확인하세요.</span></div><ol id="kl-log" class="kl-log"></ol></div><dialog id="kl-help-dialog" class="kl-dialog"><form method="dialog"><button class="kl-dialog-close">×</button><span class="kl-badge">HOW TO TEST</span><h3>추천 테스트</h3><div class="kl-help-grid"><article><b>방패 돌진</b><p>A는 직선 진형, B는 군중에서 비교하세요.</p></article><article><b>서약 절단</b><p>A는 단일 정예, B는 군중에서 차이가 큽니다.</p></article><article><b>보조무기</b><p>메아리=재타격, 문장=다음 스킬 연계, 회수=귀환 궤적입니다.</p></article><article><b>속성</b><p>강철 경직, 화염 지속 피해, 냉기 둔화, 번개 연쇄가 실제 적용됩니다.</p></article></div></form></dialog></section>`;
const $=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)],cv=$('#kl-canvas'),c=cv.getContext('2d'),W=960,H=540,top=98,bottom=502;
const E={steel:{n:'강철',d:'경직·밀침 강화',c:'#e2d3bd'},fire:{n:'화염',d:'3회 점화',c:'#ff783d'},ice:{n:'냉기',d:'2초 둔화',c:'#7fd7ff'},lightning:{n:'번개',d:'근처 적 연쇄',c:'#ffe06a'}};
const O={echo:{n:'성벽의 메아리',d:'0.34초 뒤 45% 잔상 타격'},mark:{n:'결투의 문장',d:'첫 스킬 표식 → 다음 스킬 폭발'},return:{n:'회수 사슬',d:'0.48초 뒤 궤적이 되돌아옴'}};
const S=[['방패 돌진',.72,['철벽 돌파','직선 돌파','길게 돌진하며 좁은 경로를 강하게 밀어낸다.'],['반월 방진','근접 제어','짧게 전진하고 넓은 반월 방패 타격으로 군중을 밀친다.']],['방패폭풍',2.2,['압축 공전','근접 지속','세 방패가 3초 공전하며 접근한 적을 반복 타격한다.'],['확장 회오리','광역 제압','대형 방패 충격파가 확장되며 주변 적을 밀어낸다.']],['연쇄 돌격',2.65,['기사의 추격','추적 연계','가까운 적 최대 3체를 순서대로 추격한다.'],['수호 귀환','왕복 경로','전방 돌진 후 출발점으로 돌아오며 왕복 모두 타격한다.']],['서약 절단',1.05,['처형 베기','단일 압축','좁고 무거운 검격. 정예에게 높은 피해와 강한 경직.'],['진형 붕괴','광역 절단','넓은 횡베기로 다수의 적을 걷어내 진형을 무너뜨린다.']],['수호의 맹세',4.4,['반격 서약','타이밍 반격','1.5초 방어. 공격을 받으면 즉시 강한 반격.'],['수호진','지역 수비','4초 보호진. 받는 피해 감소와 주기적 제압.']]];
const img={};for(const[k,u]of Object.entries({knight:'./assets/knight-apprentice.svg',dummy:'./assets/training-dummy.svg',shield:'./assets/knight-shield.svg',slash:'./assets/slash-arc.svg'})){img[k]=new Image;img[k].src=u}
const st={skill:0,form:0,el:'steel',off:'echo',dir:{x:1,y:0},keys:new Set,layout:'crowd',p:{x:190,y:310,hp:100,max:100,speed:205,guard:0,parry:0,zone:0},en:[],fx:[],flo:[],orbit:0,orbitTick:0,cd:S.map(()=>0),last:performance.now(),cast:0,shake:0};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),norm=(x,y)=>{let l=Math.hypot(x,y)||1;return{x:x/l,y:y/l}},dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),now=()=>performance.now()/1000,ad=(a,b)=>{let d=a-b;while(d>Math.PI)d-=Math.PI*2;while(d<-Math.PI)d+=Math.PI*2;return Math.abs(d)};
function log(t){let li=document.createElement('li');li.textContent=t;$('#kl-log').prepend(li);while($('#kl-log').children.length>7)$('#kl-log').lastElementChild.remove()}
let tt;function toast(t){$('#kl-toast').textContent=t;$('#kl-toast').classList.add('show');clearTimeout(tt);tt=setTimeout(()=>$('#kl-toast').classList.remove('show'),1000)}
function enemy(x,y,elite=false){return{x,y,r:elite?31:25,hp:elite?760:310,max:elite?760:310,s:elite?42:52,elite,dead:false,flash:0,stag:0,slow:0,burn:[],mark:0,markCast:-1,atk:Math.random()*.7}}
function reset(l=st.layout){st.layout=l;st.p.x=190;st.p.y=310;st.p.hp=100;st.p.guard=st.p.parry=st.p.zone=0;st.orbit=0;st.fx=[];st.en=l==='duel'?[enemy(660,310,true)]:l==='line'?[enemy(470,310),enemy(590,310),enemy(710,310),enemy(830,310,true)]:[enemy(540,220),enemy(630,270),enemy(690,365),enemy(555,400),enemy(785,245),enemy(805,390,true)];$('#kl-stage-title').textContent='훈련 진형 · '+({duel:'단일 정예',line:'직선 진형',crowd:'군중전'}[l]);log('↻ 훈련 진형을 재배치했습니다.');$('#kl-frame').focus({preventScroll:true})}
function ui(){$('#kl-skill-list').innerHTML=S.map((s,i)=>`<button class="kl-skill ${i===st.skill?'active':''}" data-s="${i}"><span class="kl-skill-num">0${i+1}</span><span><b>${s[0]}</b><small>${s[2+st.form][1]}</small></span><kbd>${i+1}</kbd></button>`).join('');let s=S[st.skill];$('#kl-forms').innerHTML=[0,1].map(i=>`<button class="kl-form ${i===st.form?'active':''}" data-f="${i}"><span>${i?'B':'A'}</span><div><b>${s[2+i][0]}</b><small>${s[2+i][1]}</small><p>${s[2+i][2]}</p></div></button>`).join('');$('#kl-hotbar').innerHTML=S.map((s,i)=>`<button data-h="${i}" class="${i===st.skill?'active':''} ${st.cd[i]>0?'cooling':''}"><span>${i+1}</span><b>${s[0]}</b><i>${st.cd[i]>0?st.cd[i].toFixed(1):''}</i></button>`).join('');$('#kl-read-skill').textContent=s[0]+' · '+s[2+st.form][0];$('#kl-read-element').textContent=E[st.el].n+' · '+E[st.el].d;$('#kl-read-offhand').textContent=O[st.off].n;$('#kl-rule-card').innerHTML=`<span>현재 조합</span><b>${s[2+st.form][1]} + ${O[st.off].n}</b><p>${O[st.off].d}</p>`;$$('[data-s]').forEach(b=>b.onclick=()=>sel(+b.dataset.s));$$('[data-f]').forEach(b=>b.onclick=()=>form(+b.dataset.f));$$('[data-h]').forEach(b=>b.onclick=()=>sel(+b.dataset.h))}
function sel(i){st.skill=i;st.form=0;ui();toast((i+1)+'. '+S[i][0])}function form(i){st.form=i;ui();toast((i?'B · ':'A · ')+S[st.skill][2+i][0])}
function fx(type,o={}){st.fx.push({type,t:now(),dur:o.dur||.5,color:E[st.el].c,...o})}function fl(x,y,t,k='d'){st.flo.push({x,y,t,k,l:.8})}
function raw(e,d,label=''){if(!e||e.dead)return;e.hp-=d;e.flash=.12;$('#kl-read-damage').textContent=Math.round(d);fl(e.x,e.y-e.r-12,Math.round(d)+label,label?'s':'d');if(e.hp<=0){e.dead=true;fl(e.x,e.y-40,'BREAK','b');fx('burst',{x:e.x,y:e.y})}}
function element(e,d,sx,sy){let t=now();if(st.el==='steel'){let q=norm(e.x-sx,e.y-sy);e.x+=q.x*28;e.y+=q.y*28;e.stag=.25;fl(e.x,e.y-45,'경직','s')}if(st.el==='fire')for(let i=1;i<=3;i++)e.burn.push({t:t+i*.45,d:Math.max(8,d*.1)});if(st.el==='ice'){e.slow=t+2;fl(e.x,e.y-45,'둔화','s');fx('frost',{x:e.x,y:e.y})}if(st.el==='lightning'){st.en.filter(x=>!x.dead&&x!==e&&dist(x,e)<170).slice(0,2).forEach((x,i)=>setTimeout(()=>{raw(x,d*.42,'⚡');fx('bolt',{x:e.x,y:e.y,x2:x.x,y2:x.y,dur:.18})},50+i*60))}}
function hit(e,d,id,sx=st.p.x,sy=st.p.y,kb=0){if(!e||e.dead)return;let t=now();if(st.off==='mark'){if(e.mark>t&&e.markCast!==id){raw(e,d*.35,'✦');e.mark=0;fx('burst',{x:e.x,y:e.y})}else if(e.mark<=t){e.mark=t+4;e.markCast=id;fl(e.x,e.y-45,'표식','s')}}raw(e,d);element(e,d,sx,sy);if(kb){let q=norm(e.x-sx,e.y-sy);e.x+=q.x*kb;e.y+=q.y*kb}}
const circle=(x,y,r)=>st.en.filter(e=>!e.dead&&Math.hypot(e.x-x,e.y-y)<=r+e.r),cone=(x,y,dir,r,a)=>{let ba=Math.atan2(dir.y,dir.x);return st.en.filter(e=>!e.dead&&Math.hypot(e.x-x,e.y-y)<=r+e.r&&ad(Math.atan2(e.y-y,e.x-x),ba)<=a)},seg=(px,py,ax,ay,bx,by)=>{let X=bx-ax,Y=by-ay,L=X*X+Y*Y||1,t=clamp(((px-ax)*X+(py-ay)*Y)/L,0,1);return Math.hypot(px-(ax+X*t),py-(ay+Y*t))},line=(a,b,w)=>st.en.filter(e=>!e.dead&&seg(e.x,e.y,a.x,a.y,b.x,b.y)<=w+e.r*.5);
function doSkill(base,m=1,echo=false){let p=st.p,s=base.s,f=base.f,d=base.dir,id=base.id;if(s===0){if(f===0){let a={x:p.x,y:p.y},b={x:clamp(a.x+d.x*(echo?115:205),45,W-45),y:clamp(a.y+d.y*(echo?115:205),top+35,bottom-25)};if(!echo){p.x=b.x;p.y=b.y}fx('rush',{x:a.x,y:a.y,x2:b.x,y2:b.y,dur:.38});line(a,b,34).forEach(e=>hit(e,118*m,id,a.x,a.y,34))}else{if(!echo){p.x=clamp(p.x+d.x*48,45,W-45);p.y=clamp(p.y+d.y*48,top+35,bottom-25);p.guard=now()+1}fx('fan',{x:p.x,y:p.y,dir:d,r:150});cone(p.x,p.y,d,150,1.12).forEach(e=>hit(e,82*m,id,p.x,p.y,42))}}
if(s===1){if(f===0){if(!echo){st.orbit=now()+3;st.orbitTick=0}else circle(p.x,p.y,115).forEach(e=>hit(e,37*m,id));fx('wave',{x:p.x,y:p.y,r:115})}else{fx('wave',{x:p.x,y:p.y,r:235,dur:.75});circle(p.x,p.y,235).forEach(e=>hit(e,88*m,id,p.x,p.y,55))}}
if(s===2){if(f===0){st.en.filter(e=>!e.dead).sort((a,b)=>dist(a,p)-dist(b,p)).slice(0,echo?1:3).forEach((e,i)=>setTimeout(()=>{if(e.dead)return;let a={x:p.x,y:p.y},q=norm(e.x-p.x,e.y-p.y);p.x=e.x-q.x*42;p.y=e.y-q.y*42;st.dir=q;fx('rush',{x:a.x,y:a.y,x2:p.x,y2:p.y,dur:.26});hit(e,(76+i*12)*m,id,a.x,a.y,18)},130*(i+1)))}else{let a={x:p.x,y:p.y},b={x:clamp(a.x+d.x*(echo?130:230),45,W-45),y:clamp(a.y+d.y*(echo?130:230),top+35,bottom-25)};if(!echo){p.x=b.x;p.y=b.y}fx('rush',{x:a.x,y:a.y,x2:b.x,y2:b.y,dur:.32});line(a,b,34).forEach(e=>hit(e,68*m,id,a.x,a.y,15));setTimeout(()=>{fx('rush',{x:b.x,y:b.y,x2:a.x,y2:a.y,dur:.32});line(b,a,34).forEach(e=>hit(e,82*m,id,b.x,b.y,18));if(!echo){p.x=a.x;p.y=a.y;p.guard=now()+.7}},270)}}
if(s===3){if(f===0){fx('slash',{x:p.x,y:p.y,dir:d,r:145,narrow:true});cone(p.x,p.y,d,155,.42).forEach(e=>hit(e,164*m*(e.elite?1.12:1),id,p.x,p.y,24))}else{fx('slash',{x:p.x,y:p.y,dir:d,r:190,narrow:false});cone(p.x,p.y,d,190,1.15).forEach(e=>hit(e,92*m,id,p.x,p.y,62))}}
if(s===4){if(f===0){p.parry=now()+(echo?.55:1.5);p.guard=p.parry;fx('guard',{x:p.x,y:p.y,r:76,dur:echo?.6:1.5})}else{p.zone=now()+(echo?1.2:4);fx('zone',{x:p.x,y:p.y,r:145,dur:echo?1.2:4});circle(p.x,p.y,145).forEach(e=>hit(e,42*m,id,p.x,p.y,22))}}}
function cast(){let i=st.skill;if(st.cd[i]>0){toast('재사용 대기 '+st.cd[i].toFixed(1)+'초');return}st.cd[i]=S[i][1];let base={s:i,f:st.form,dir:{...st.dir},id:++st.cast,x:st.p.x,y:st.p.y};doSkill(base);if(st.off==='echo')setTimeout(()=>{doSkill(base,.45,true);log('↳ 성벽의 메아리: 잔상 타격')},340);if(st.off==='return'){let a={x:base.x,y:base.y},b={x:clamp(a.x+base.dir.x*220,40,W-40),y:clamp(a.y+base.dir.y*220,top+30,bottom-20)};setTimeout(()=>{fx('rush',{x:b.x,y:b.y,x2:a.x,y2:a.y,dur:.5});line(b,a,38).forEach(e=>hit(e,58,base.id,b.x,b.y,12));log('↳ 회수 사슬: 귀환 판정')},480)}log('⚔ '+S[i][0]+' · '+S[i][2+st.form][0]+' / '+E[st.el].n+' / '+O[st.off].n);toast(S[i][0]+' · '+S[i][2+st.form][0]);st.shake=.12;ui()}
function parry(){if(st.p.parry<=now())return false;st.p.parry=0;st.p.guard=now()+.6;let id=++st.cast;circle(st.p.x,st.p.y,185).forEach(e=>hit(e,178,id,st.p.x,st.p.y,75));fx('wave',{x:st.p.x,y:st.p.y,r:190});fl(st.p.x,st.p.y-70,'PARRY!','b');log('🛡 반격 서약 성공');return true}
function update(dt){let p=st.p,mx=0,my=0;if(st.keys.has('KeyW')||st.keys.has('ArrowUp'))my--;if(st.keys.has('KeyS')||st.keys.has('ArrowDown'))my++;if(st.keys.has('KeyA')||st.keys.has('ArrowLeft'))mx--;if(st.keys.has('KeyD')||st.keys.has('ArrowRight'))mx++;if(mx||my){let q=norm(mx,my);st.dir=q;p.x=clamp(p.x+q.x*p.speed*dt,38,W-38);p.y=clamp(p.y+q.y*p.speed*dt,top+28,bottom-18)}st.cd=st.cd.map(x=>Math.max(0,x-dt));st.fx=st.fx.filter(x=>now()-x.t<x.dur);st.flo.forEach(x=>{x.l-=dt;x.y-=25*dt});st.flo=st.flo.filter(x=>x.l>0);st.shake=Math.max(0,st.shake-dt);let t=now();st.en.forEach(e=>{if(e.dead)return;e.flash=Math.max(0,e.flash-dt);e.stag=Math.max(0,e.stag-dt);e.atk-=dt;let due=e.burn.filter(b=>b.t<=t);e.burn=e.burn.filter(b=>b.t>t);due.forEach(b=>raw(e,b.d,'🔥'));if(e.stag>0)return;let q=norm(p.x-e.x,p.y-e.y),dd=dist(e,p),sp=e.s*(e.slow>t?.48:1);if(dd>50){e.x+=q.x*sp*dt;e.y+=q.y*sp*dt}if(dd<60&&e.atk<=0){e.atk=e.elite?1.05:1.35;if(parry())return;let d=e.elite?13:7;if(p.zone>t)d*=.52;if(p.guard>t)d*=.58;p.hp=Math.max(0,p.hp-d);fl(p.x,p.y-65,'-'+Math.round(d),'h')}});if(st.orbit>t){st.orbitTick-=dt;if(st.orbitTick<=0){st.orbitTick=.42;circle(p.x,p.y,118).forEach(e=>hit(e,37,++st.cast,p.x,p.y,5))}}if(p.zone>t&&Math.floor(t*2)!==Math.floor((t-dt)*2))circle(p.x,p.y,145).forEach(e=>{raw(e,16);e.slow=Math.max(e.slow,t+.7)});if(p.hp<=0){p.hp=100;p.x=190;p.y=310;toast('훈련장 보호: 회복')}$('#kl-hp-fill').style.width=p.hp+'%';$('#kl-hp-text').textContent=Math.ceil(p.hp)+' / 100';$('#kl-status').textContent=p.parry>t?'반격 대기':p.zone>t?'수호진':st.orbit>t?'공전 방패':p.guard>t?'가드':'준비';$$('#kl-hotbar button').forEach((b,i)=>{b.classList.toggle('cooling',st.cd[i]>0);let z=b.querySelector('i');if(z)z.textContent=st.cd[i]>0?st.cd[i].toFixed(1):''})}
function image(im,x,y,w,h,r=0,a=1){c.save();c.translate(x,y);c.rotate(r);c.globalAlpha=a;if(im.complete&&im.naturalWidth)c.drawImage(im,-w/2,-h/2,w,h);else{c.fillStyle='#b9aa98';c.fillRect(-w/4,-h/3,w/2,h*.66)}c.restore()}
function drawFx(f){let p=clamp((now()-f.t)/f.dur,0,1),a=1-p;c.save();c.globalCompositeOperation='lighter';c.globalAlpha=a;c.strokeStyle=f.color;c.fillStyle=f.color;c.shadowColor=f.color;c.shadowBlur=18;c.lineCap='round';if(f.type==='rush'||f.type==='bolt'){c.lineWidth=f.type==='bolt'?6:16;c.beginPath();c.moveTo(f.x,f.y);c.lineTo(f.x2,f.y2);c.stroke()}if(f.type==='wave'||f.type==='burst'){c.lineWidth=12;c.beginPath();c.arc(f.x,f.y,(f.r||60)*(.2+p),0,Math.PI*2);c.stroke()}if(f.type==='fan'){let q=Math.atan2(f.dir.y,f.dir.x);c.lineWidth=18;c.beginPath();c.arc(f.x,f.y,f.r*(.55+p*.4),q-1.1,q+1.1);c.stroke();image(img.shield,f.x+f.dir.x*65,f.y+f.dir.y*65,58,68,q,a)}if(f.type==='slash'){let q=Math.atan2(f.dir.y,f.dir.x),sp=f.narrow?.46:1.15;c.lineWidth=f.narrow?15:12;c.beginPath();c.arc(f.x,f.y,f.r*(.7+p*.24),q-sp,q+sp);c.stroke();image(img.slash,f.x+Math.cos(q)*f.r*.6,f.y+Math.sin(q)*f.r*.6,f.narrow?175:230,f.narrow?90:120,q,a)}if(f.type==='guard'||f.type==='zone'){c.lineWidth=f.type==='zone'?4:8;c.beginPath();c.arc(f.x,f.y,f.r,0,Math.PI*2);c.stroke();c.globalAlpha=a*.12;c.beginPath();c.arc(f.x,f.y,f.r,0,Math.PI*2);c.fill()}if(f.type==='frost'){c.lineWidth=3;for(let i=0;i<8;i++){let q=i*Math.PI/4;c.beginPath();c.moveTo(f.x,f.y);c.lineTo(f.x+Math.cos(q)*45*p,f.y+Math.sin(q)*45*p);c.stroke()}}c.restore()}
function draw(){c.save();if(st.shake>0)c.translate((Math.random()-.5)*7,(Math.random()-.5)*5);let g=c.createLinearGradient(0,0,0,H);g.addColorStop(0,'#191a1b');g.addColorStop(.18,'#242220');g.addColorStop(1,'#11100f');c.fillStyle=g;c.fillRect(0,0,W,H);c.fillStyle='#0b0b0c';c.fillRect(0,0,W,82);for(let y=110;y<H;y+=52)for(let x=(Math.floor(y/52)%2)*-36;x<W;x+=112){c.strokeStyle='rgba(154,126,98,.10)';c.strokeRect(x,y,108,48)}st.fx.filter(f=>f.type==='zone'||f.type==='guard').forEach(drawFx);let t=now();st.en.forEach(e=>{if(e.dead)return;c.save();if(e.mark>t){c.strokeStyle='#f8d781';c.setLineDash([5,5]);c.beginPath();c.arc(e.x,e.y,e.r+15,0,Math.PI*2);c.stroke()}if(e.flash>0)c.globalAlpha=.45;image(img.dummy,e.x,e.y, e.elite?82:68,e.elite?104:88);let w=e.elite?82:64;c.fillStyle='#111';c.fillRect(e.x-w/2,e.y-61,w,7);c.fillStyle=e.elite?'#d99d53':'#c7564d';c.fillRect(e.x-w/2,e.y-61,w*clamp(e.hp/e.max,0,1),7);c.restore()});let q=Math.atan2(st.dir.y,st.dir.x);image(img.knight,st.p.x,st.p.y-7,98,112,q);if(st.orbit>t)for(let i=0;i<3;i++){let a=t*2.5+i*Math.PI*2/3;image(img.shield,st.p.x+Math.cos(a)*96,st.p.y+Math.sin(a)*62,38,44,a,.9)}st.fx.filter(f=>f.type!=='zone'&&f.type!=='guard').forEach(drawFx);st.flo.forEach(f=>{c.globalAlpha=clamp(f.l/.8,0,1);c.textAlign='center';c.font=f.k==='b'?'800 20px system-ui':'800 16px system-ui';c.fillStyle=f.k==='h'?'#ff6c63':f.k==='s'?'#ffe4a1':'#fff';c.fillText(f.t,f.x,f.y)});c.restore()}
function loop(t){let dt=Math.min(.035,(t-st.last)/1000||0);st.last=t;update(dt);draw();requestAnimationFrame(loop)}
function kd(e){let a=['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyQ','KeyR','Digit1','Digit2','Digit3','Digit4','Digit5'];if(!a.includes(e.code)||!root.closest('.view.active'))return;e.preventDefault();if(e.repeat&&['Space','KeyQ','KeyR'].includes(e.code))return;st.keys.add(e.code);if(e.code==='Space')cast();if(e.code==='KeyQ')form(1-st.form);if(e.code==='KeyR')reset();if(/^Digit[1-5]$/.test(e.code))sel(+e.code.slice(-1)-1)}document.addEventListener('keydown',kd,{passive:false});document.addEventListener('keyup',e=>st.keys.delete(e.code));$('#kl-cast').onclick=cast;$$('[data-layout]').forEach(b=>b.onclick=()=>reset(b.dataset.layout));$('#kl-element').onchange=e=>{st.el=e.target.value;ui();log('◆ 주무기 속성: '+E[st.el].n+' — '+E[st.el].d)};$('#kl-offhand').onchange=e=>{st.off=e.target.value;ui();log('◇ 보조무기: '+O[st.off].n+' — '+O[st.off].d)};$('#kl-help').onclick=()=>$('#kl-help-dialog').showModal();ui();reset('crowd');log('✓ 실제 판정 기반 견습기사 체험장 준비 완료.');requestAnimationFrame(loop)
}
